### ISSUE TITLE
Warning during compilation of project using periscope lib.

### ISSUE THREAD

**Issue by PZiaugra** [caleb-bb/periscope#10]
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
 Periscope.MixProject.project/0

warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
Periscope.MixProject.project/0

**Comment by caleb-bb** [comment]
Hey! This has been solved already, per our Slack discussion. Upgrading to version 0.1.2 will fix. Putting this comment here for record purposes.
